### ISSUE TITLE
Soccer não é com c?

### ISSUE THREAD

**Issue by rubenmarcus** [clovisdasilvaneto/CsSocker#4]
Como joga? Não tem instruções basicas de como jogar

**Comment by clovisdasilvaneto** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkk, Não é soccer de futebol, foi uma aposta que fiz com alguns amigos e ficou socker com 'k' mesmo... Mas vou mudar porque você não é o primeiro que me pergunta isso ahauhauhauhauha. 

Para jogar é so tentar clicar no boneco, se você conseguir ele chuta a bola para a rede e faz gol, se não; ele chuta para fora
